import type { ExternalLink } from '@/types/external-link';

const checkedAt = '2026-06-22';

function seed(
  link: Omit<ExternalLink, 'createdAt' | 'updatedAt' | 'lastCheckedAt'>
): ExternalLink {
  return {
    ...link,
    lastCheckedAt: checkedAt,
    createdAt: checkedAt,
    updatedAt: checkedAt,
  };
}

export const externalLinkSeeds: ExternalLink[] = [
  seed({
    id: 'iaap',
    slug: 'international-association-for-analytical-psychology',
    name: 'International Association for Analytical Psychology',
    abbreviation: 'IAAP',
    description: {
      th: 'สมาคมนานาชาติสำหรับนักวิเคราะห์และสมาคมวิชาชีพด้านจิตวิทยาวิเคราะห์',
      en: 'International association for analytical psychologists and member societies.',
    },
    url: 'https://iaap.org/',
    category: 'analytical_psychology',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ทางการของ IAAP', en: 'Official IAAP website.' },
    language: 'English',
    country: 'International',
    isOfficial: true,
    isRecommended: true,
    status: 'active',
  }),
  seed({
    id: 'sap',
    slug: 'society-of-analytical-psychology',
    name: 'Society of Analytical Psychology',
    abbreviation: 'SAP',
    description: {
      th: 'องค์กรวิชาชีพและสถาบันฝึกอบรม Jungian analysis ในสหราชอาณาจักร',
      en: 'UK professional body and training institute for Jungian analysis.',
    },
    url: 'https://www.thesap.org.uk/',
    category: 'analytical_psychology',
    linkType: 'institute',
    authorityNote: { th: 'เว็บไซต์ทางการของ SAP', en: 'Official SAP website.' },
    language: 'English',
    country: 'United Kingdom',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'iajs',
    slug: 'international-association-for-jungian-studies',
    name: 'International Association for Jungian Studies',
    abbreviation: 'IAJS',
    description: {
      th: 'สมาคมสหสาขาวิชาสำหรับ Jungian และ post-Jungian studies',
      en: 'Multidisciplinary association for Jungian and post-Jungian studies.',
    },
    url: 'https://jungstudies.net/',
    category: 'analytical_psychology',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ของสมาคม IAJS', en: 'IAJS association website.' },
    language: 'English',
    country: 'International',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'jcss',
    slug: 'jungian-center-for-the-spiritual-sciences',
    name: 'Jungian Center for the Spiritual Sciences',
    abbreviation: 'JCSS',
    description: {
      th: 'ศูนย์การศึกษาที่เผยแพร่หลักสูตรและบทความเกี่ยวกับ Jungian psychology',
      en: 'Educational center offering courses and essays on Jungian psychology.',
    },
    url: 'https://jungiancenter.org/',
    category: 'analytical_psychology',
    linkType: 'educational_center',
    authorityNote: {
      th: 'โดเมนองค์กรควรตรวจสถานะเป็นระยะ',
      en: 'Organization domain; review availability periodically.',
    },
    language: 'English',
    country: 'United States',
    isOfficial: false,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'ipa',
    slug: 'international-psychoanalytical-association',
    name: 'International Psychoanalytical Association',
    abbreviation: 'IPA',
    description: {
      th: 'องค์กรสมาชิกและหน่วยรับรองระดับนานาชาติด้านจิตวิเคราะห์',
      en: 'International membership and accrediting organization for psychoanalysis.',
    },
    url: 'https://www.ipa.world/',
    category: 'psychoanalysis',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ทางการของ IPA', en: 'Official IPA website.' },
    language: 'English',
    country: 'International',
    isOfficial: true,
    isRecommended: true,
    status: 'active',
  }),
  seed({
    id: 'apsaa',
    slug: 'american-psychoanalytic-association',
    name: 'American Psychoanalytic Association',
    abbreviation: 'APsA',
    description: {
      th: 'สมาคมวิชาชีพอเมริกันสำหรับนักคลินิก นักการศึกษา และนักวิจัยด้านจิตวิเคราะห์',
      en: 'US professional association for psychoanalytic clinicians, educators, and researchers.',
    },
    url: 'https://apsa.org/',
    category: 'psychoanalysis',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ทางการของ APsA', en: 'Official APsA website.' },
    language: 'English',
    country: 'United States',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'sep',
    slug: 'stanford-encyclopedia-of-philosophy',
    name: 'Stanford Encyclopedia of Philosophy',
    abbreviation: 'SEP',
    description: {
      th: 'สารานุกรมปรัชญาที่เขียนและปรับปรุงโดยนักวิชาการเฉพาะสาขา',
      en: 'Scholarly philosophy encyclopedia maintained by subject specialists.',
    },
    url: 'https://plato.stanford.edu/',
    category: 'philosophy',
    linkType: 'encyclopedia',
    authorityNote: { th: 'โครงการของ Stanford University', en: 'A Stanford University project.' },
    language: 'English',
    country: 'United States',
    isOfficial: true,
    isRecommended: true,
    status: 'active',
  }),
  seed({
    id: 'iep',
    slug: 'internet-encyclopedia-of-philosophy',
    name: 'Internet Encyclopedia of Philosophy',
    abbreviation: 'IEP',
    description: {
      th: 'สารานุกรมออนไลน์ที่เผยแพร่บทความโดยนักปรัชญามืออาชีพ',
      en: 'Online encyclopedia publishing articles by professional philosophers.',
    },
    url: 'https://iep.utm.edu/',
    category: 'philosophy',
    linkType: 'encyclopedia',
    authorityNote: { th: 'สารานุกรมวิชาการแบบเปิด', en: 'Open scholarly encyclopedia.' },
    language: 'English',
    country: 'United States',
    isOfficial: true,
    isRecommended: true,
    status: 'active',
  }),
  seed({
    id: 'philpapers',
    slug: 'philpapers',
    name: 'PhilPapers',
    abbreviation: null,
    description: {
      th: 'ดัชนีและบรรณานุกรมงานวิจัยทางปรัชญาที่ดูแลโดยชุมชนนักปรัชญา',
      en: 'Research index and bibliography maintained by the philosophy community.',
    },
    url: 'https://philpapers.org/',
    category: 'philosophy_of_mind',
    linkType: 'reference_site',
    authorityNote: { th: 'ดัชนีวิชาการเฉพาะทาง', en: 'Specialist academic index.' },
    language: 'English',
    country: 'International',
    isOfficial: true,
    isRecommended: true,
    status: 'active',
  }),
  seed({
    id: 'sfn',
    slug: 'society-for-neuroscience',
    name: 'Society for Neuroscience',
    abbreviation: 'SfN',
    description: {
      th: 'สมาคมนักวิทยาศาสตร์และแพทย์ที่ศึกษาสมองและระบบประสาท',
      en: 'Professional society for scientists and physicians studying the brain and nervous system.',
    },
    url: 'https://www.sfn.org/',
    category: 'neuroscience',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ทางการของ SfN', en: 'Official SfN website.' },
    language: 'English',
    country: 'United States',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'spsp',
    slug: 'society-for-personality-and-social-psychology',
    name: 'Society for Personality and Social Psychology',
    abbreviation: 'SPSP',
    description: {
      th: 'สมาคมวิชาการด้านบุคลิกภาพและจิตวิทยาสังคม',
      en: 'Scientific society for personality and social psychology.',
    },
    url: 'https://spsp.org/',
    category: 'social_psychology',
    linkType: 'association',
    authorityNote: { th: 'เว็บไซต์ทางการของ SPSP', en: 'Official SPSP website.' },
    language: 'English',
    country: 'United States',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'tsc',
    slug: 'the-souls-compass',
    name: 'The Soul’s Compass',
    abbreviation: 'TSC',
    description: {
      th: 'คลังความรู้สองภาษาเกี่ยวกับจิตวิทยา ปรัชญา และจิตใจมนุษย์',
      en: 'Bilingual knowledge archive about psychology, philosophy, and mind.',
    },
    url: 'https://thesoulscompass.com/',
    category: 'internal',
    linkType: 'internal_project',
    authorityNote: { th: 'โครงการภายใน', en: 'Internal project.' },
    language: 'Thai / English',
    country: 'Thailand',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
  seed({
    id: 'tpdt',
    slug: 'transformative-psyche-dynamics-theory',
    name: 'Transformative Psyche Dynamics Theory',
    abbreviation: 'TPDT',
    description: {
      th: 'กรอบทฤษฎีภายในที่อยู่ระหว่างการพัฒนาและแยกจากฉันทามติภายนอกอย่างชัดเจน',
      en: 'Internal theory-in-development, explicitly separated from external consensus.',
    },
    url: 'https://thesoulscompass.com/th/tpdt',
    category: 'internal',
    linkType: 'internal_project',
    authorityNote: { th: 'กรอบทฤษฎีภายใน', en: 'Internal theoretical framework.' },
    language: 'Thai',
    country: 'Thailand',
    isOfficial: true,
    isRecommended: false,
    status: 'active',
  }),
];
