import type { Series } from '@/types/series';

export const thaiSeries = [
  {
    id: 'series-structure-of-psyche-th',
    slug: 'structure-of-the-psyche',
    title: 'โครงสร้างของจิต',
    subtitle: 'จาก Ego และ Persona สู่ Shadow, Self และ Individuation',
    description:
      'เส้นทางปูพื้นฐานสำหรับทำความเข้าใจว่าจิตวิทยาวิเคราะห์แบ่งส่วนและความสัมพันธ์ภายใน Psyche อย่างไร โดยไม่ลดแนวคิดให้เป็นป้ายบุคลิกภาพ',
    introduction:
      'เริ่มจากขอบเขตของจิตสำนึกและบทบาททางสังคม จากนั้นค่อยเข้าสู่สิ่งที่ Ego ไม่รวมเป็นตน ก่อนวาง Self และ Individuation ไว้ในฐานะกรอบของความเป็นทั้งหมดและการเปลี่ยนแปลงระยะยาว',
    language: 'th',
    type: 'foundation',
    category: 'analytical-psychology',
    difficulty: 'beginner',
    status: 'completed',
    coverImage: null,
    estimatedReadingTime: 45,
    articleCount: 1,
    conceptCount: 4,
    author: 'Witcha Prasomsin',
    publishedAt: '2026-06-22',
    updatedAt: '2026-06-22',
    seoTitle: 'โครงสร้างของจิต: เส้นทางอ่านจิตวิทยาของ Jung',
    seoDescription:
      'เส้นทางอ่าน Ego, Persona, Shadow, Self และ Individuation สำหรับเริ่มต้นศึกษาจิตวิทยาวิเคราะห์อย่างเป็นลำดับ',
    items: [
      {
        id: 'series-psyche-01',
        seriesId: 'series-structure-of-psyche-th',
        order: 1,
        type: 'concept',
        targetId: 'concept-ego-jung-th',
        title: 'Ego — ศูนย์กลางของจิตสำนึก',
        description:
          'กำหนดขอบเขตของ “ฉัน” ใน Jung และแยก Ego ออกจาก Psyche ทั้งหมด',
        required: true,
        estimatedReadingTime: 5,
      },
      {
        id: 'series-psyche-02',
        seriesId: 'series-structure-of-psyche-th',
        order: 2,
        type: 'concept',
        targetId: 'concept-persona-th',
        title: 'Persona — บทบาทที่ใช้พบโลก',
        description:
          'อ่านหน้ากากทางสังคมในฐานะหน้าที่จำเป็น พร้อมข้อจำกัดเมื่อ Ego ยึดติดกับบทบาท',
        required: true,
        estimatedReadingTime: 5,
      },
      {
        id: 'series-psyche-03',
        seriesId: 'series-structure-of-psyche-th',
        order: 3,
        type: 'article',
        targetId: 'article-shadow-not-dark-side-th',
        title: 'Shadow ไม่ใช่แค่ด้านมืด',
        description:
          'บทความเชื่อม Persona, Shadow และ Projection โดยไม่ทำให้เงากลายเป็นคำเรียกความชั่วร้าย',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-psyche-04',
        seriesId: 'series-structure-of-psyche-th',
        order: 4,
        type: 'note',
        targetId: 'note-anima-animus-position',
        title: 'ตำแหน่งของ Anima / Animus ในระบบเดิมของ Jung',
        description:
          'บันทึกสำหรับชะลอการใช้คำแบบเหมารวมทางเพศ และวางแนวคิดนี้ไว้ในบริบทประวัติศาสตร์ก่อนมีโหนดฉบับเต็ม',
        required: false,
        estimatedReadingTime: 3,
      },
      {
        id: 'series-psyche-05',
        seriesId: 'series-structure-of-psyche-th',
        order: 5,
        type: 'concept',
        targetId: 'concept-self-jung-th',
        title: 'Self — ความเป็นทั้งหมดที่กว้างกว่า Ego',
        description:
          'ทำความเข้าใจ Self ในฐานะหลักการจัดระเบียบ ไม่ใช่ตัวตนแท้แบบคำขวัญ',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-psyche-06',
        seriesId: 'series-structure-of-psyche-th',
        order: 6,
        type: 'concept',
        targetId: 'concept-individuation-th',
        title: 'Individuation — ความสัมพันธ์ระหว่างส่วนต่าง ๆ ของ Psyche',
        description:
          'ปิดเส้นทางด้วยกระบวนการถอนภาพฉาย เผชิญ Shadow และคลายการยึดติดกับ Persona',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-psyche-07',
        seriesId: 'series-structure-of-psyche-th',
        order: 7,
        type: 'reference',
        targetId: 'jung-two-essays-1928',
        title: 'Two Essays on Analytical Psychology',
        description:
          'งานหลักสำหรับอ่านความสัมพันธ์ระหว่าง Ego, unconscious และกระบวนการพัฒนาบุคลิกภาพในภาษาของ Jung เอง',
        required: false,
        estimatedReadingTime: 12,
      },
    ],
    suggestedSeries: [
      'from-jung-to-lacan',
      'tpdt-transformative-psyche-dynamics',
    ],
    translations: {},
  },
  {
    id: 'series-psychoanalysis-foundations-th',
    slug: 'introduction-to-psychoanalysis',
    title: 'จิตวิเคราะห์เบื้องต้น',
    subtitle: 'Unconscious, Drive, Repression, Defense และการก่อตัวของอาการ',
    description:
      'เส้นทางเริ่มต้นสำหรับอ่านจิตวิเคราะห์ของ Freud ผ่านกลไกและความขัดแย้ง ไม่ใช่ผ่านรายการศัพท์ที่แยกขาดจากกัน',
    introduction:
      'ลำดับนี้เริ่มจากคำถามว่ากระบวนการที่เราไม่รู้ตัวมีผลอย่างไร แล้วค่อยติดตามแรงเรียกร้องของ Drive การกีดกันด้วย Repression การจัดการความวิตกกังวลด้วย Defense และตำแหน่งของ Ego ในความขัดแย้ง',
    language: 'th',
    type: 'foundation',
    category: 'psychoanalysis',
    difficulty: 'beginner',
    status: 'active',
    coverImage: null,
    estimatedReadingTime: 55,
    articleCount: 1,
    conceptCount: 5,
    author: 'Witcha Prasomsin',
    publishedAt: '2026-06-22',
    updatedAt: '2026-06-22',
    seoTitle: 'จิตวิเคราะห์เบื้องต้น: เส้นทางอ่าน Freud',
    seoDescription:
      'เส้นทางอ่าน Unconscious, Drive, Repression, Defense Mechanism และ Ego สำหรับเริ่มต้นศึกษาจิตวิเคราะห์อย่างเป็นระบบ',
    items: [
      {
        id: 'series-freud-01',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 1,
        type: 'concept',
        targetId: 'concept-unconscious-freud-th',
        title: 'Unconscious — กระบวนการที่ไม่โปร่งใสต่อตนเอง',
        description:
          'เริ่มจากมิติของจิตที่ไม่เข้าถึงโดยตรง แต่ปรากฏผ่านความฝัน อาการ และการกระทำ',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-freud-02',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 2,
        type: 'concept',
        targetId: 'concept-drive-th',
        title: 'Drive — แรงเรียกร้องต่อการทำงานของจิต',
        description:
          'แยก Drive ออกจากสัญชาตญาณ ความต้องการ และความอยากในความหมายทั่วไป',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-freud-03',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 3,
        type: 'concept',
        targetId: 'concept-repression-th',
        title: 'Repression — การกีดกันที่ยังคงออกฤทธิ์',
        description:
          'อ่านการกดไว้ในฐานะกระบวนการต่อเนื่อง ไม่ใช่การลบความทรงจำออกจากคลัง',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-freud-04',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 4,
        type: 'concept',
        targetId: 'concept-defense-mechanism-th',
        title: 'Defense Mechanism — วิธีจัดการความขัดแย้ง',
        description:
          'วางกลไกป้องกันไว้ในความสัมพันธ์กับความวิตกกังวลและหน้าที่ของ Ego',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-freud-05',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 5,
        type: 'article',
        targetId: 'article-freud-jung-ego-th',
        title: 'Ego ใน Freud กับ Jung ต่างกันอย่างไร',
        description:
          'ใช้การเปรียบเทียบเพื่อทำให้หน้าที่ของ Ego ในระบบ Freud ชัดขึ้น โดยไม่ผสมสองทฤษฎีเข้าด้วยกัน',
        required: true,
        estimatedReadingTime: 8,
      },
      {
        id: 'series-freud-06',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 6,
        type: 'concept',
        targetId: 'concept-ego-freud-th',
        title: 'Ego (Freud) — ตัวกลางที่ไม่เป็นนายในบ้านตนเอง',
        description:
          'กลับมาอ่าน Ego โดยตรงหลังมีกรอบของ Drive, Repression และ Defense แล้ว',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-freud-07',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 7,
        type: 'note',
        targetId: 'note-symptom-compromise-formation',
        title: 'อาการในฐานะ compromise formation',
        description:
          'บันทึกสั้นเพื่อเชื่อมแรงขับ การป้องกัน และการกลับมาของสิ่งที่ถูกกด ก่อนมีบทความเรื่อง symptom ฉบับเต็ม',
        required: true,
        estimatedReadingTime: 5,
      },
      {
        id: 'series-freud-08',
        seriesId: 'series-psychoanalysis-foundations-th',
        order: 8,
        type: 'reference',
        targetId: 'freud-inhibitions-1926',
        title: 'Inhibitions, Symptoms and Anxiety',
        description:
          'งานอ้างอิงหลักสำหรับติดตามความสัมพันธ์ระหว่างความวิตกกังวล การป้องกัน และอาการ',
        required: false,
        estimatedReadingTime: 12,
      },
    ],
    suggestedSeries: ['from-jung-to-lacan'],
    translations: {},
  },
  {
    id: 'series-jung-lacan-comparative-th',
    slug: 'from-jung-to-lacan',
    title: 'จาก Jung ถึง Lacan',
    subtitle: 'Ego, Self, Unconscious, Language และ Desire ข้ามสองระบบทฤษฎี',
    description:
      'เส้นทางเปรียบเทียบระดับลึกที่รักษาความต่างระหว่างจิตวิทยาวิเคราะห์กับจิตวิเคราะห์แบบ Lacan แทนการจับคำคล้ายกันมาเท่ากัน',
    introduction:
      'เส้นทางนี้ใช้ Ego และ unconscious เป็นจุดตั้งต้น แล้วเปลี่ยนแกนจากความเป็นทั้งหมดของ Psyche ไปสู่ภาษา ความขาด และ Desire ใน Lacan เป้าหมายไม่ใช่เลือกผู้ชนะ แต่ดูว่าแต่ละระบบตั้งคำถามคนละแบบอย่างไร',
    language: 'th',
    type: 'comparative',
    category: 'comparative-psychology',
    difficulty: 'advanced',
    status: 'active',
    coverImage: null,
    estimatedReadingTime: 72,
    articleCount: 1,
    conceptCount: 7,
    author: 'Witcha Prasomsin',
    publishedAt: '2026-06-22',
    updatedAt: '2026-06-22',
    seoTitle: 'จาก Jung ถึง Lacan: เส้นทางอ่านเปรียบเทียบ',
    seoDescription:
      'เปรียบเทียบ Ego, Self, Unconscious, Language, Desire และ Symbolic ระหว่าง Jung, Freud และ Lacan อย่างเป็นลำดับ',
    items: [
      {
        id: 'series-jung-lacan-01',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 1,
        type: 'article',
        targetId: 'article-freud-jung-ego-th',
        title: 'เริ่มจากคำเดียวที่ทำงานต่างกัน: Ego',
        description:
          'ตั้งหลักด้วยความต่างระหว่างศูนย์กลางของ consciousness กับตัวกลางของความขัดแย้ง',
        required: true,
        estimatedReadingTime: 8,
      },
      {
        id: 'series-jung-lacan-02',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 2,
        type: 'concept',
        targetId: 'concept-self-jung-th',
        title: 'Self ใน Jung — ความเป็นทั้งหมดของ Psyche',
        description:
          'อ่านแรงโน้มสู่ wholeness ก่อนเปลี่ยนไปสู่ subject ที่ถูกแบ่งด้วยภาษา',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-jung-lacan-03',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 3,
        type: 'concept',
        targetId: 'concept-unconscious-freud-th',
        title: 'Unconscious ใน Freud — ความขัดแย้งและการกดไว้',
        description:
          'วางฐานจิตวิเคราะห์ก่อนเข้าสู่การอ่าน unconscious ผ่านโครงสร้างของ signifier',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-jung-lacan-04',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 4,
        type: 'concept',
        targetId: 'concept-imaginary-lacan-th',
        title: 'Imaginary — เอกภาพผ่านภาพและการระบุตัว',
        description:
          'สำรวจภาพของความเป็นหนึ่งเดียวที่ช่วยก่อ Ego แต่ไม่ทำให้ subject สมบูรณ์',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-jung-lacan-05',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 5,
        type: 'concept',
        targetId: 'concept-symbolic-lacan-th',
        title: 'Symbolic — ภาษา กฎ และตำแหน่งของ subject',
        description:
          'เปลี่ยนจากภาพภายในจิตไปสู่ระเบียบของความแตกต่างที่มีอยู่ก่อนปัจเจก',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-jung-lacan-06',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 6,
        type: 'concept',
        targetId: 'concept-desire-lacan-th',
        title: 'Desire — สิ่งที่ไม่ยุติลงด้วยการเติมเต็ม need',
        description:
          'อ่าน Desire ผ่าน Lack, Demand และความสัมพันธ์กับ Big Other',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-jung-lacan-07',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 7,
        type: 'concept',
        targetId: 'concept-big-other-lacan-th',
        title: 'Big Other — ตำแหน่งที่ค้ำประกันความหมาย',
        description:
          'แยก Other ออกจากบุคคลผู้มีอำนาจ และติดตามบทบาทของภาษาและการรับรอง',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-jung-lacan-08',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 8,
        type: 'concept',
        targetId: 'concept-real-lacan-th',
        title: 'Real — ขีดจำกัดของภาพและภาษา',
        description:
          'ปิดเส้นทางด้วยสิ่งที่ต้านการทำให้เป็นภาพรวมหรือระบบสัญลักษณ์ที่สมบูรณ์',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-jung-lacan-09',
        seriesId: 'series-jung-lacan-comparative-th',
        order: 9,
        type: 'reference',
        targetId: 'lacan-seminar-xi-1964',
        title: 'The Four Fundamental Concepts of Psychoanalysis',
        description:
          'จุดอ่านต่อสำหรับ unconscious, repetition, transference และ drive ในการสอนของ Lacan',
        required: false,
        estimatedReadingTime: 18,
      },
    ],
    suggestedSeries: [
      'structure-of-the-psyche',
      'introduction-to-psychoanalysis',
    ],
    translations: {},
  },
  {
    id: 'series-tpdt-foundations-th',
    slug: 'tpdt-transformative-psyche-dynamics',
    title: 'TPDT: ทฤษฎีพลวัตทางจิตเชิงการเปลี่ยนผ่าน',
    subtitle: 'Psyche, Defense, Transformation และรูปแบบช่วงเปลี่ยนผ่าน',
    description:
      'เส้นทางที่กำลังพัฒนาสำหรับอ่าน TPDT ในฐานะกรอบวิเคราะห์กระบวนการ ไม่ใช่ระบบติดป้ายประเภทบุคลิกภาพสำเร็จรูป',
    introduction:
      'เริ่มจากคำถามว่ารูปแบบภายในเคลื่อนไหวและรักษาเสถียรภาพอย่างไร จากนั้นติดตามสนามการป้องกัน เงื่อนไขของการเปลี่ยนแปลง และรูปแบบชั่วคราวที่เกิดระหว่างโครงสร้างเดิมกับการจัดระเบียบใหม่',
    language: 'th',
    type: 'tpdt',
    category: 'tpdt',
    difficulty: 'intermediate',
    status: 'active',
    coverImage: null,
    estimatedReadingTime: 48,
    articleCount: 1,
    conceptCount: 4,
    author: 'Witcha Prasomsin',
    publishedAt: '2026-06-22',
    updatedAt: '2026-06-22',
    seoTitle: 'TPDT: เส้นทางอ่านพลวัต การป้องกัน และการเปลี่ยนผ่าน',
    seoDescription:
      'เส้นทางอ่าน Psyche Dynamics, Defense Field, Transformation Axis และ Transitional Pattern ใน TPDT ซึ่งยังอยู่ระหว่างพัฒนา',
    items: [
      {
        id: 'series-tpdt-01',
        seriesId: 'series-tpdt-foundations-th',
        order: 1,
        type: 'article',
        targetId: 'article-what-is-tpdt-th',
        title: 'TPDT คืออะไร',
        description:
          'เริ่มด้วยขอบเขตของทฤษฎี สถานะที่ยังพัฒนา และความต่างจากระบบจำแนกบุคลิกภาพทั่วไป',
        required: true,
        estimatedReadingTime: 6,
      },
      {
        id: 'series-tpdt-02',
        seriesId: 'series-tpdt-foundations-th',
        order: 2,
        type: 'concept',
        targetId: 'concept-psyche-dynamics-tpdt-th',
        title: 'Psyche Dynamics — อ่านจิตในฐานะกระบวนการ',
        description:
          'ติดตาม activation, inhibition, compensation และการเปลี่ยนรูปของ patterns',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-tpdt-03',
        seriesId: 'series-tpdt-foundations-th',
        order: 3,
        type: 'concept',
        targetId: 'concept-defense-field-tpdt-th',
        title: 'Defense Field — การป้องกันแบบกระจายตัว',
        description:
          'ขยายจากกลไกเดี่ยวไปสู่เครือข่าย intrapsychic, interpersonal และ contextual',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-tpdt-04',
        seriesId: 'series-tpdt-foundations-th',
        order: 4,
        type: 'concept',
        targetId: 'concept-transformation-axis-tpdt-th',
        title: 'Transformation Axis — มิติของการเปลี่ยนรูป',
        description:
          'อ่านความแข็งตัว การสะท้อนคิด การทดลอง และการจัดระเบียบใหม่โดยไม่ทำเป็นคะแนนความดี',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-tpdt-05',
        seriesId: 'series-tpdt-foundations-th',
        order: 5,
        type: 'concept',
        targetId: 'concept-transitional-pattern-tpdt-th',
        title: 'Transitional Pattern — รูปแบบที่ยังไม่ลงตัว',
        description:
          'วางความไม่เสถียรไว้ในฐานะข้อมูลของการเปลี่ยนผ่าน ไม่ใช่ความล้มเหลวทันที',
        required: true,
        estimatedReadingTime: 7,
      },
      {
        id: 'series-tpdt-06',
        seriesId: 'series-tpdt-foundations-th',
        order: 6,
        type: 'reference',
        targetId: 'winnicott-playing-reality-1971',
        title: 'Playing and Reality',
        description:
          'งานอ่านเปรียบเทียบสำหรับคิดเรื่องพื้นที่ทดลอง ความไม่แน่นอน และการก่อรูปสิ่งใหม่',
        required: false,
        estimatedReadingTime: 14,
      },
    ],
    suggestedSeries: [
      'structure-of-the-psyche',
      'introduction-to-psychoanalysis',
    ],
    translations: {},
  },
] as const satisfies readonly Series[];
