import type { ConceptReference } from '@/types/concept';

export const conceptReferences = {
  jungTypes: {
    id: 'jung-psychological-types-1921',
    authors: 'Jung, C. G.',
    year: 1921,
    title: 'Psychological Types',
    publication: 'Collected Works, Vol. 6',
  },
  jungTwoEssays: {
    id: 'jung-two-essays-1928',
    authors: 'Jung, C. G.',
    year: 1928,
    title: 'Two Essays on Analytical Psychology',
    publication: 'Collected Works, Vol. 7',
  },
  jungDynamics: {
    id: 'jung-structure-dynamics',
    authors: 'Jung, C. G.',
    year: 1960,
    title: 'The Structure and Dynamics of the Psyche',
    publication: 'Collected Works, Vol. 8',
  },
  jungArchetypes: {
    id: 'jung-archetypes-collective-unconscious',
    authors: 'Jung, C. G.',
    year: 1959,
    title: 'The Archetypes and the Collective Unconscious',
    publication: 'Collected Works, Vol. 9i',
  },
  jungAion: {
    id: 'jung-aion-1951',
    authors: 'Jung, C. G.',
    year: 1951,
    title: 'Aion: Researches into the Phenomenology of the Self',
    publication: 'Collected Works, Vol. 9ii',
  },
  freudDreams: {
    id: 'freud-interpretation-dreams-1900',
    authors: 'Freud, S.',
    year: 1900,
    title: 'The Interpretation of Dreams',
    publication: 'Standard Edition, Vols. 4–5',
  },
  freudRepression: {
    id: 'freud-repression-1915',
    authors: 'Freud, S.',
    year: 1915,
    title: 'Repression',
    publication: 'Standard Edition, Vol. 14',
  },
  freudUnconscious: {
    id: 'freud-unconscious-1915',
    authors: 'Freud, S.',
    year: 1915,
    title: 'The Unconscious',
    publication: 'Standard Edition, Vol. 14',
  },
  freudBeyondPleasure: {
    id: 'freud-beyond-pleasure-1920',
    authors: 'Freud, S.',
    year: 1920,
    title: 'Beyond the Pleasure Principle',
    publication: 'Standard Edition, Vol. 18',
  },
  freudEgoId: {
    id: 'freud-ego-id-1923',
    authors: 'Freud, S.',
    year: 1923,
    title: 'The Ego and the Id',
    publication: 'Standard Edition, Vol. 19',
  },
  freudAnxiety: {
    id: 'freud-inhibitions-1926',
    authors: 'Freud, S.',
    year: 1926,
    title: 'Inhibitions, Symptoms and Anxiety',
    publication: 'Standard Edition, Vol. 20',
  },
  annaFreudDefense: {
    id: 'anna-freud-ego-defense-1936',
    authors: 'Freud, A.',
    year: 1936,
    title: 'The Ego and the Mechanisms of Defence',
  },
  lacanEcrits: {
    id: 'lacan-ecrits-1966',
    authors: 'Lacan, J.',
    year: 1966,
    title: 'Écrits',
  },
  lacanSeminarXI: {
    id: 'lacan-seminar-xi-1964',
    authors: 'Lacan, J.',
    year: 1964,
    title: 'The Four Fundamental Concepts of Psychoanalysis',
    publication: 'The Seminar of Jacques Lacan, Book XI',
  },
  chalmersConsciousMind: {
    id: 'chalmers-conscious-mind-1996',
    authors: 'Chalmers, D. J.',
    year: 1996,
    title: 'The Conscious Mind',
  },
  nagelBat: {
    id: 'nagel-what-is-it-like-1974',
    authors: 'Nagel, T.',
    year: 1974,
    title: 'What Is It Like to Be a Bat?',
    publication: 'The Philosophical Review, 83(4)',
  },
  brentanoPsychology: {
    id: 'brentano-psychology-1874',
    authors: 'Brentano, F.',
    year: 1874,
    title: 'Psychology from an Empirical Standpoint',
  },
  searleIntentionality: {
    id: 'searle-intentionality-1983',
    authors: 'Searle, J. R.',
    year: 1983,
    title: 'Intentionality: An Essay in the Philosophy of Mind',
  },
  zahaviSubjectivity: {
    id: 'zahavi-subjectivity-selfhood-2005',
    authors: 'Zahavi, D.',
    year: 2005,
    title: 'Subjectivity and Selfhood',
  },
  winnicottPlaying: {
    id: 'winnicott-playing-reality-1971',
    authors: 'Winnicott, D. W.',
    year: 1971,
    title: 'Playing and Reality',
  },
  hebbOrganization: {
    id: 'hebb-organization-behavior-1949',
    authors: 'Hebb, D. O.',
    year: 1949,
    title: 'The Organization of Behavior',
  },
  kandelMemory: {
    id: 'kandel-molecular-memory-2001',
    authors: 'Kandel, E. R.',
    year: 2001,
    title: 'The Molecular Biology of Memory Storage',
    publication: 'Science, 294(5544)',
  },
  fristonFreeEnergy: {
    id: 'friston-free-energy-2010',
    authors: 'Friston, K.',
    year: 2010,
    title: 'The Free-Energy Principle: A Unified Brain Theory?',
    publication: 'Nature Reviews Neuroscience, 11',
  },
  clarkSurfingUncertainty: {
    id: 'clark-surfing-uncertainty-2016',
    authors: 'Clark, A.',
    year: 2016,
    title: 'Surfing Uncertainty',
  },
  craigInteroception: {
    id: 'craig-interoception-2002',
    authors: 'Craig, A. D.',
    year: 2002,
    title: 'How Do You Feel? Interoception: The Sense of the Physiological Condition of the Body',
    publication: 'Nature Reviews Neuroscience, 3',
  },
  mcgaughConsolidation: {
    id: 'mcgaugh-memory-consolidation-2000',
    authors: 'McGaugh, J. L.',
    year: 2000,
    title: 'Memory—A Century of Consolidation',
    publication: 'Science, 287(5451)',
  },
  menonNetworks: {
    id: 'menon-triple-network-2011',
    authors: 'Menon, V.',
    year: 2011,
    title: 'Large-Scale Brain Networks and Psychopathology: A Unifying Triple Network Model',
    publication: 'Trends in Cognitive Sciences, 15(10)',
  },
  tajfelSocialIdentity: {
    id: 'tajfel-turner-social-identity-1979',
    authors: 'Tajfel, H., & Turner, J. C.',
    year: 1979,
    title: 'An Integrative Theory of Intergroup Conflict',
    publication: 'The Social Psychology of Intergroup Relations',
  },
  heiderRelations: {
    id: 'heider-interpersonal-relations-1958',
    authors: 'Heider, F.',
    year: 1958,
    title: 'The Psychology of Interpersonal Relations',
  },
  rossIntuitivePsychologist: {
    id: 'ross-intuitive-psychologist-1977',
    authors: 'Ross, L.',
    year: 1977,
    title: 'The Intuitive Psychologist and His Shortcomings',
    publication: 'Advances in Experimental Social Psychology, Vol. 10',
  },
  festingerDissonance: {
    id: 'festinger-dissonance-1957',
    authors: 'Festinger, L.',
    year: 1957,
    title: 'A Theory of Cognitive Dissonance',
  },
  aschConformity: {
    id: 'asch-social-pressure-1955',
    authors: 'Asch, S. E.',
    year: 1955,
    title: 'Opinions and Social Pressure',
    publication: 'Scientific American, 193(5)',
  },
  turnerSelfCategorization: {
    id: 'turner-self-categorization-1987',
    authors: 'Turner, J. C., et al.',
    year: 1987,
    title: 'Rediscovering the Social Group',
  },
  husserlIdeas: {
    id: 'husserl-ideas-1913',
    authors: 'Husserl, E.',
    year: 1913,
    title: 'Ideas Pertaining to a Pure Phenomenology',
  },
  merleauPontyPerception: {
    id: 'merleau-ponty-perception-1945',
    authors: 'Merleau-Ponty, M.',
    year: 1945,
    title: 'Phenomenology of Perception',
  },
  clarkChalmersExtendedMind: {
    id: 'clark-chalmers-extended-mind-1998',
    authors: 'Clark, A., & Chalmers, D. J.',
    year: 1998,
    title: 'The Extended Mind',
    publication: 'Analysis, 58(1)',
  },
  frankfurtAlternatePossibilities: {
    id: 'frankfurt-alternate-possibilities-1969',
    authors: 'Frankfurt, H. G.',
    year: 1969,
    title: 'Alternate Possibilities and Moral Responsibility',
    publication: 'The Journal of Philosophy, 66(23)',
  },
  parfitReasonsPersons: {
    id: 'parfit-reasons-persons-1984',
    authors: 'Parfit, D.',
    year: 1984,
    title: 'Reasons and Persons',
  },
} as const satisfies Record<string, ConceptReference>;
